title: Block, Dodge, Parry SRD
description: The System Reference Document for Block, Dodge, Parry
theme: just-the-docs

url: https://lars1808.github.io/Block-Dodge-Parry-SRD-2

# Set a path/url to a logo that will be displayed instead of the title
logo: "https://dicegoblin.blog/wp-content/uploads/2025/03/BDPSRD.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'



aux_links:
  Related Blogs: https://dicegoblin.blog/category/block-dodge-parry/
  Itch.io: https://dicegoblingames.itch.io/block-dodge-parry
  DriveThruRPG: https://www.drivethrurpg.com/en/product/425888/block-dodge-parry-a-levelless-classless-expansion-of-cairn

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
markup / liquid-based content.
footer_content: "Copyright &copy; Lars Huijbregts.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

