title: Block, Dodge, Parry SRD
description: The System Reference Document for Block, Dodge, Parry
theme: just-the-docs

url: https://lars1808.github.io/Block-Dodge-Parry-SRD-2

aux_links:
  Template Repository: https://github.com/lars1808/Block-Dodge-Parry-SRD-2
