title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lars1808.github.io/Block-Dodge-Parry-SRD-2

aux_links:
  Template Repository: https://github.com/lars1808/Block-Dodge-Parry-SRD-2
